version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: node_assignment_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_db
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
